name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Get Go dependencies
        run: go mod download

      - name: Build Binaries
        run: |
          mkdir dist # Create directory for binaries
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/fs-linux-amd64 cmd/main.go
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/fs-windows-amd64.exe cmd/main.go
          # macOS AMD64 (Intel)
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/fs-macos-amd64 cmd/main.go
          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/fs-macos-arm64 cmd/main.go
        env:
          CGO_ENABLED: 1 # gocui likely needs CGO

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
